[build]
  publish = "public"
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/server.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = ""
  publish = "public"

[context.deploy-preview]
  command = ""
  publish = "public" 